version: '3.8'

services:
  web:
    build: .
    container_name: bitrix-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web/html:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./web/apache-config:/etc/apache2/sites-available
    environment:
      - MYSQL_HOST=bitrix-db
      - MYSQL_DATABASE=bitrix
      - MYSQL_USER=bitrix
      - MYSQL_PASSWORD=bitrix_password
    networks:
      - bitrix-network
    depends_on:
      - db
    command: >
      bash -c "a2ensite ppau0.com.conf && apache2-foreground"

  db:
    image: mariadb:10.6
    container_name: bitrix-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - bitrix-network

volumes:
  db-data:

networks:
  bitrix-network:
    driver: bridge
