chmod +x "unpack (tar.bz2).sh"
./"unpack (tar.bz2).sh"
chmod -x "unpack (tar.bz2).sh"
chmod +x "unpack (tar.gz).sh"
./"unpack (tar.gz).sh"
chmod -x "unpack (tar.gz).sh"
chmod +x "unpack (tar.xz).sh"
./"unpack (tar.xz).sh"
chmod -x "unpack (tar.xz).sh"
chmod +x "unpack (zip).sh"
./"unpack (zip).sh"
chmod -x "unpack (zip).sh"
