version: '3.8'
services:
  chrome:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chrome-browser
    ports:
      - "9222:9222" # Порт для удалённой отладки Chrome
    volumes:
      - chrome-data:/home/chromeuser
    environment:
      - DISPLAY=:99
    restart: unless-stopped

volumes:
  chrome-data:
